### ISSUE TITLE
Code refuses to run. (Код отказывается запускаться.)

### ISSUE THREAD

**Issue by ghost** [SS13/luna#6]
We cant get this code to run for some reason, we have attempted to setup the database and such but it doesnt work. when someone trys to join it crashes.

Мы не можем получить этот код, чтобы выполняться по каким-либо причинам, мы попытались для установки базы данных и такие, но это не работает. когда кто-то пробует присоединиться он выходит из строя.

**Comment by ZLOFENIX** [comment]
Win/nix? Can byond connect to db? On linux it needs lots of libraries. If can - has you added at least 1 admin to db? Also what in logs when crashed?

**Comment by ghost** [comment]
Logs i dont have, yes, it is running on Linux. it connects to the DB and we have added a admin.

**Comment by ZLOFENIX** [comment]
Run in terminal and add option -log log.txt may be it will help, i dont have test linux with db to test this build.

**Comment by ghost** [comment]
Could i get a list of the libraries?

**Comment by ZLOFENIX** [comment]
I dunno lol.
I need those libraries only to connect to db, i just installed almost all libs which have mysql connector in name. On clean system byond were unable to connect to mysql.
Debian 6 squeeze, minimal, no system utilities.

**Comment by ghost** [comment]
My server is running Debian 6.0 64-bit at the moment.
Via Ramnode.

**Comment by minecrafter** [comment]
Hello there, I manage the VPS for Kerbal22. I'm watching the thread via GitHub so I will get updates.

Can you detail what libraries you used, and where to install them? I'm not a BYOND server administrator that often, nor even a user (Linux support is non-existent it seems).

**Comment by ZLOFENIX** [comment]
If it starts and can connect to db - you dont need any additional libs, error in somewhere in code. And use logging with -log param to DreamDaemon to find why its crashing. Use DreamDaemon -h for more.

**Comment by ghost** [comment]
Could you do a walk-though guide on how to set it all up?

**Comment by ZLOFENIX** [comment]
Download
Unpack
Install db
Edit configs
Use
Profit

When we were used this build - it was working without crashes.
Use logs already and post it here.

**Comment by minecrafter** [comment]
Sorry, he is just very impatient. I have not had a lot of time to peruse this, though.
